---
title: "Experiment 2"
author: "Christina Reimer"
date: "2020 07 06"
output:
  pdf_document: default
  word_document: default
  html_document: default
---


```{r setup, include=TRUE, echo=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


```{r load libraries, warning=FALSE, message=FALSE, echo=FALSE}
library(afex)
library(BayesFactor)
library(car)
library(cowplot)
library(DataCombine)
library(data.table)
library(extrafont)
library(ez)
library(ggpubr)
library(gridExtra)
library(knitr)
library(tidyverse)
```


```{r load data Exp2, warning=FALSE, echo=FALSE}
# clear directory
rm(list=ls()) 


# open files
input_Exp2 = data.frame()

files <- dir(path = "../../Data/Raw", pattern = "CIA_Preparation_Exp2_*")

for (i in files) {
  
  tmp <- read_csv(file = file.path("../../Data/Raw/", i), col_types = cols())
  
  # add the files to the data frame
  input_Exp2 = rbind (input_Exp2, tmp)
  rm(tmp)
}


# select UPPSP data
UPPSP_Exp2 = input_Exp2 %>%
  filter(factor %in% c("Perseverance", "Premeditation", "Positive Urgency", "Negative Urgency", "Sensation Seeking"))
# rename prolific_ID into participant
names(UPPSP_Exp2)[1] = "participant" 


# select TIPI data
TIPI_Exp2 = input_Exp2 %>%
   filter(factor == 'Conscientiousness_TIPI')
# rename prolific_ID into participant
names(TIPI_Exp2)[1] = "participant" 


# select BHI data
BHI_Exp2 = input_Exp2 %>%
   filter(factor == 'Conscientiousness_BHI')
# rename prolific_ID into participant
names(BHI_Exp2)[1] = "participant" 


# convert some factor variables to numeric variables
input_Exp2$block_number = as.numeric(as.character(input_Exp2$block_number))
input_Exp2$prepRT = as.numeric(as.character(input_Exp2$prepRT))
input_Exp2$rt = as.numeric(as.character(input_Exp2$rt))


# add numeric equivalent for correct variable; correct = TRUE = 1, correct = FALSE = 0
input_Exp2 = input_Exp2 %>%
  mutate(acc = correct)
input_Exp2$acc = as.integer(as.logical(input_Exp2$acc)) 


# filter questionnaire data for the analysis
input_Exp2 = input_Exp2 %>%
  filter(block_number <= 96)


# block_type: rename 1 to 50%-image-alone, rename 0 to 100%-image-alone
input_Exp2$block_type[input_Exp2$block_type == "25"] = "25%-image-alone"
input_Exp2$block_type[input_Exp2$block_type == "75"] = "75%-image-alone"


# rename prolific_ID into participant
names(input_Exp2)[1] = "participant"


# demographics
demographics = input_Exp2 %>%
  summarise(mean= mean(age), 
            sd= sd(age), 
            max = max(age),
            min = min(age))


gender = input_Exp2 %>%
  filter(block_number == "1") %>%
  group_by(gender) %>%
  count()
```


#### Experiment 2
#### PrepRT analysis depending on condition (i.e., 75%-image-alone vs 25%-image-alone)
```{r Exp2 prepRT analysis and plot, warning=FALSE, message=FALSE, echo=FALSE}
# remove outliers and calculate prepRT depending on condition
prepRT2 = input_Exp2 %>%
  filter(prepRT > 100) %>%
  filter(prepRT < 20000) %>%
  filter(rt > 100) %>% 
  filter(rt < 3000) %>%
  group_by(participant, block_type) %>%
  summarise(prepRT = mean(prepRT)) 


prepRT2_GM = prepRT2 %>%
  group_by(block_type) %>%
  summarise(
    prepRT = mean(prepRT))
kable(prepRT2_GM, caption = "PrepRT depending on condition", digits = 2) 


# calculate removed trials in %
#100 - ((100/9984)*9728)


# z transform prepRT
prepRT2_cor = input_Exp2 %>%
  filter(prepRT > 100) %>%
  filter(prepRT < 20000) %>%
  filter(rt > 100) %>% 
  filter(rt < 3000) %>%
  filter(block_type == "75%-image-alone") %>%
  group_by(participant) %>%
  #mutate(prepRT_z = scale(prepRT, center = TRUE, scale = TRUE)) %>%
  summarise(prepRT = mean(prepRT))


# pairwise comparisons including NHST and Bayes t-tests for PrepRT depending on condition
source("pairwise_comparisons.R") #pw

prepRT2_wide = prepRT2 %>%
  dcast(participant ~ block_type, value.var = "prepRT")

prepRT2_wide_pw = TES(prepRT2_wide$`75%-image-alone`, prepRT2_wide$`25%-image-alone`, paired=TRUE) 

row.names(prepRT2_wide_pw) = c('PrepRT')
kable(prepRT2_wide_pw, caption = "Paired-samples t-test on PrepRT", digits = 2)


# plot prepRT
level_order = c('75%-image-alone', '25%-image-alone')

plot_PrepRT2 = ggplot(prepRT2, aes(x = factor(block_type, level = level_order), y = prepRT)) +
  geom_line(aes(group = participant), colour = "grey") +
  geom_point() +
  geom_boxplot(colour = "black", fill="grey", alpha = 0, width=0.1) +
  
  scale_y_continuous(breaks = c(2000,4000,6000,8000,10000,12000,14000), limits = c(2000,14000)) +
  
  stat_summary(fun.prepRT=mean, colour = "red", geom="line", aes(group=1))  + 
  stat_summary(fun.prepRT=mean, colour = "red", geom="point") +
  stat_summary(fun.data = mean_cl_normal, colour = "red", width = 0.1, geom = "errorbar") +
  
  xlab("Condition") +
  ylab("Preparation RT (ms)") + 
      
  ggtitle("Preparation depending on condition") + 
  theme(plot.title = element_text(hjust = 0.5)) +
    
  theme(text = element_text(face = "plain", size = 14)) +
  theme(axis.text = element_text(size = 14, color = "black")) +
  theme(axis.title.x = element_text(face = "plain", size = 14)) +
  theme(axis.title.x = element_text(margin = margin(t = 16, r = 0, b = 0, l = 00))) +
  theme(axis.title.y = element_text(face = "plain", size = 14)) +
  theme(axis.title.y = element_text(margin = margin(t = 0, r = 16, b = 0, l = 0))) +
  theme(axis.ticks = element_line(size = 1)) +
    
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
  panel.background = element_blank(), axis.line = element_line(colour = "black"))

plot_PrepRT2
#ggsave("plot_PrepRT2.png", width = 24, height = 16, units = "cm")
``` 


\newpage 
#### Performance on image-alone trials depending on condition (i.e., 75%-image-alone vs 25%-image-alone)
```{r Exp2 ACC and exeRT image-alone trials, warning=FALSE, message=FALSE, echo=FALSE}
# ACC
# exclude prepRT and exeRT outliers and image-and-letter trials
# calculate mean ACC
ACC_imageonly2 = input_Exp2 %>%
  filter(prepRT > 100) %>%
  filter(prepRT < 20000) %>%
  filter(rt > 100) %>% 
  filter(rt < 3000) %>%
  filter(letter_block == 0) %>%
  group_by(participant, block_type) %>%
  summarise(ACC = mean(acc))

ACC_imageonly2_GM = ACC_imageonly2 %>%
  group_by(block_type) %>%
  summarise(
    ACC = mean(ACC))
kable(ACC_imageonly2_GM, caption = "ACC on image-alone trials depending on condition", digits = 2) 


# paired-samples t-test
source("pairwise_comparisons.R")
ACC_imageonly2_wide = ACC_imageonly2 %>%
  dcast(participant ~ block_type, value.var = "ACC")

ACC_imageonly2_pw = TES(ACC_imageonly2_wide$`75%-image-alone`, ACC_imageonly2_wide$`25%-image-alone`, paired=TRUE)

row.names(ACC_imageonly2_pw) = c('ACC')
kable(ACC_imageonly2_pw, caption = "Paired-samples t-test on ACC", digits = 2) 


# Correct exeRT
# exclude prepRT and exeRT outliers as well as incorrect trials and image-and-letter trials
# calculate mean exeRT
RT_imageonly2 = input_Exp2 %>%
  filter(prepRT > 100) %>%
  filter(prepRT < 20000) %>%
  filter(rt > 100) %>% 
  filter(rt < 3000) %>%
  filter(correct == "true") %>%
  filter(letter_block == 0) %>%
  group_by(participant, block_type) %>%
  summarise(RT = mean(rt))

RT_imageonly2_GM = RT_imageonly2 %>%
  group_by(block_type) %>%
  summarise(
    RT = mean(RT))
kable(RT_imageonly2_GM, caption = "ExeRT on image-alone trials depending on condition", digits = 2) 


# calculate removed trials (i.e., incorrect trials) in %
#100 - ((100/9728)*8773)


# paired-samples t-test
source("pairwise_comparisons.R")
RT_imageonly2_wide = RT_imageonly2 %>%
  dcast(participant ~ block_type, value.var = "RT")

RT_imageonly2_pw = TES(RT_imageonly2_wide$`75%-image-alone`, RT_imageonly2_wide$`25%-image-alone`, paired=TRUE)

row.names(RT_imageonly2_pw) = c('ExeRT')
kable(RT_imageonly2_pw, caption = "Paired-samples t-test on exeRT", digits = 2) 
```


\newpage 
#### Performance on image-and-letter trials
```{r Exp2 ACC and exeRT image-and-letter trials, warning=FALSE, message=FALSE, echo=FALSE}
# ACC
# exclude prepRT and exeRT outliers and image-alone trials
# calculate mean ACC
ACC_imageletter2 = input_Exp2 %>%
  filter(prepRT > 100) %>%
  filter(prepRT < 20000) %>%
  filter(rt > 100) %>% 
  filter(rt < 3000) %>%
  filter(letter_block == 1) %>%
  group_by(participant, block_type) %>%
  summarise(ACC = mean(acc))

ACC_imageletter2_GM = ACC_imageletter2 %>%
  group_by(block_type) %>%
  summarise(
    ACC = mean(ACC))
kable(ACC_imageletter2_GM, caption = "ACC on image-and-letter trials depending on condition", digits = 2) 


# paired-samples t-test
source("pairwise_comparisons.R")
ACC_imageletter2_wide = ACC_imageletter2 %>%
  dcast(participant ~ block_type, value.var = "ACC")

ACC_imageletter2_pw = TES(ACC_imageletter2_wide$`75%-image-alone`, ACC_imageletter2_wide$`25%-image-alone`, paired=TRUE)

row.names(ACC_imageletter2_pw) = c('ACC')
kable(ACC_imageletter2_pw, caption = "Paired-samples t-test on ACC", digits = 2) 


# Correct exeRT
# exclude prepRT and exeRT outliers as well as incorrect trials and image-alone trials
# calculate mean exeRT
RT_imageletter2 = input_Exp2 %>%
  filter(prepRT > 100) %>%
  filter(prepRT < 20000) %>%
  filter(rt > 100) %>% 
  filter(rt < 3000) %>%
  filter(correct == "true") %>%
  filter(letter_block == 1) %>%
  group_by(participant, block_type) %>%
  summarise(RT = mean(rt))

RT_imageletter2_GM = RT_imageletter2 %>%
  group_by(block_type) %>%
  summarise(
    RT = mean(RT))
kable(RT_imageletter2_GM, caption = "ExeRT on image-and-letter trials depending on condition", digits = 2) 


# calculate removed trials (i.e., incorrect trials) in %
#100 - ((100/4620)*4100) ### change number of trials


# paired-samples t-test
source("pairwise_comparisons.R")
RT_imageletter2_wide = RT_imageletter2 %>%
  dcast(participant ~ block_type, value.var = "RT")

RT_imageletter2_pw = TES(RT_imageletter2_wide$`75%-image-alone`, RT_imageletter2_wide$`25%-image-alone`, paired=TRUE)

row.names(RT_imageletter2_pw) = c('ExeRT')
kable(RT_imageletter2_pw, caption = "Paired-samples t-test on exeRT", digits = 2) 
```


\newpage 
#### Pair-split analysis
```{r Exp2 pair-split analysis, warning=FALSE, message=FALSE, echo=FALSE}
input_pairsplit_Exp2 = input_Exp2 %>% 
  filter(block_type == "75%-image-alone") %>%
  filter(letter_block == "0") %>%
  arrange(participant, block_number) %>% 
  mutate(pair = ceiling(block_number/2)) %>% # create pair number based on block number; block 1 and 2 will be pair 1, etc.
  group_by(participant, pair) %>%
  mutate(n_block_in_pair = n(), # count number of blocks in a pair; due to missing data, some 'pair's have only one block
         Pair_PrepRT = mean(prepRT), # calculate the mean prepRT of each pair
         fasterPreparation = (prepRT < Pair_PrepRT), # determine whether each block is the one with shorter prepRT in the pair
         diff = prepRT - Pair_PrepRT) %>% # calculate the difference between raw prepRT and the average of each pair 
  filter(n_block_in_pair == 2, # select only pairs that have two blocks
         diff != 0) # select pairs where the prepRT of the two blocks differ 


# check: each participant should have equal number of faster and slower blocks
#table(input_pairsplit_Exp2$participant, input_pairsplit_Exp2$fasterPreparation)


# calculate mean prepRT depending on pair-split
prepRT_pairsplit2 = input_pairsplit_Exp2 %>%
  filter(prepRT > 100) %>%
  filter(prepRT < 20000) %>%
  filter(rt > 100) %>% 
  filter(rt < 3000) %>%
  group_by(participant, fasterPreparation) %>%
  summarise(prepRT = mean(prepRT)) 


prepRT_pairsplit2_GM = prepRT_pairsplit2 %>%
  group_by(fasterPreparation) %>%
  summarise(
    prepRT = mean(prepRT))
kable(prepRT_pairsplit2_GM, caption = "PrepRT for fast vs slow preparation", digits = 2) 


# calculate CIs for paper
prepRT_pairsplit2_forpaper = prepRT_pairsplit2 %>%
  group_by(fasterPreparation) %>%
  summarise(mean.prepRT = mean(prepRT, na.rm = TRUE),
            sd.prepRT = sd(prepRT, na.rm = TRUE),
            n.prepRT = n()) %>%
  mutate(se.prepRT = sd.prepRT / sqrt(n.prepRT),
         lower.ci.prepRT = mean.prepRT - qt(1 - (0.05 / 2), n.prepRT - 1) * se.prepRT,
         upper.ci.prepRT = mean.prepRT + qt(1 - (0.05 / 2), n.prepRT - 1) * se.prepRT)
kable(prepRT_pairsplit2_forpaper, caption = "PrepRT depending on fast vs slow preparation", digits = 2) 


# calculate mean ACC depending on pair-split
ACC_pairsplit2 = input_pairsplit_Exp2 %>%
  filter(prepRT > 100) %>%
  filter(prepRT < 20000) %>%
  filter(rt > 100) %>% 
  filter(rt < 3000) %>%
  group_by(participant, fasterPreparation) %>%
  summarise(ACC = mean(acc))

ACC_pairsplit2_GM = ACC_pairsplit2 %>%
  group_by(fasterPreparation) %>%
  summarise(
    ACC = mean(ACC))
kable(ACC_pairsplit2_GM, caption = "ACC depending on fast vs slow preparation", digits = 2) 


# calculate CIs for paper
ACC_pairsplit2_forpaper = ACC_pairsplit2 %>%
  group_by(fasterPreparation) %>%
  summarise(mean.ACC = mean(ACC, na.rm = TRUE),
            sd.ACC = sd(ACC, na.rm = TRUE),
            n.ACC = n()) %>%
  mutate(se.ACC = sd.ACC / sqrt(n.ACC),
         lower.ci.ACC = mean.ACC - qt(1 - (0.05 / 2), n.ACC - 1) * se.ACC,
         upper.ci.ACC = mean.ACC + qt(1 - (0.05 / 2), n.ACC - 1) * se.ACC)
kable(ACC_pairsplit2_forpaper, caption = "ACC depending on fast vs slow preparation", digits = 2) 


# paired-samples t-test
source("pairwise_comparisons.R")
ACC_pairsplit2_wide = ACC_pairsplit2 %>%
  dcast(participant ~fasterPreparation, value.var = "ACC")

ACC_pairsplit2_pw = TES(ACC_pairsplit2_wide$`FALSE`, ACC_pairsplit2_wide$`TRUE`, paired=TRUE)

row.names(ACC_pairsplit2_pw) = c('ACC')
kable(ACC_pairsplit2_pw, caption = "Paired-samples t-test on ACC", digits = 2) 


# calculate mean exeRT depending on pair-split
RT_pairsplit2 = input_pairsplit_Exp2 %>%
  filter(prepRT > 100) %>%
  filter(prepRT < 20000) %>%
  filter(rt > 100) %>% 
  filter(rt < 3000) %>%
  filter(correct == "true") %>%
  group_by(participant, fasterPreparation) %>%
  summarise(RT = mean(rt))

RT_pairsplit2_GM = RT_pairsplit2 %>%
  group_by(fasterPreparation) %>%
  summarise(
    RT = mean(RT))
kable(RT_pairsplit2_GM, caption = "ExeRT depending on fast vs slow preparation", digits = 2) 


# calculate CIs for paper
RT_pairsplit2_forpaper = RT_pairsplit2 %>%
  group_by(fasterPreparation) %>%
  summarise(mean.RT = mean(RT, na.rm = TRUE),
            sd.RT = sd(RT, na.rm = TRUE),
            n.RT = n()) %>%
  mutate(se.RT = sd.RT / sqrt(n.RT),
         lower.ci.RT = mean.RT - qt(1 - (0.05 / 2), n.RT - 1) * se.RT,
         upper.ci.RT = mean.RT + qt(1 - (0.05 / 2), n.RT - 1) * se.RT)
kable(RT_pairsplit2_forpaper, caption = "ExeRT depending on fast vs slow preparation", digits = 2) 


# paired-samples t-test
source("pairwise_comparisons.R")
RT_pairsplit2_wide = RT_pairsplit2 %>%
  dcast(participant ~fasterPreparation, value.var = "RT")

RT_pairsplit2_pw = TES(RT_pairsplit2_wide$`FALSE`, RT_pairsplit2_wide$`TRUE`, paired=TRUE)

row.names(RT_pairsplit2_pw) = c('RT')
kable(RT_pairsplit2_pw, caption = "Paired-samples t-test on exeRT", digits = 2) 
```


```{r Exp 2 UPPSP, warning=FALSE, message=FALSE, echo=FALSE}
# check that each participant has 20 UPPSP responses
p_no_uppsp = table(UPPSP_Exp2$participant)
#p_no_uppsp

# calculate UPPSP score for each participant for each factor
# perseverance
UPPSP_Exp2_perseverance = UPPSP_Exp2 %>%
  filter(factor == "Perseverance")

UPPSP_Exp2_perseverance$resp = as.numeric(as.character(UPPSP_Exp2_perseverance$resp))

UPPSP_Exp2_perseverance_score = UPPSP_Exp2_perseverance %>%
  group_by(participant) %>%
  summarise(Perseverance_Score = mean(resp))


# premeditation
UPPSP_Exp2_premeditation = UPPSP_Exp2 %>%
  filter(factor == "Premeditation")

UPPSP_Exp2_premeditation$resp = as.numeric(as.character(UPPSP_Exp2_premeditation$resp))

UPPSP_Exp2_premeditation_score = UPPSP_Exp2_premeditation %>%
  group_by(participant) %>%
  summarise(Premeditation_Score = mean(resp))


# positive urgency
UPPSP_Exp2_posurgency = UPPSP_Exp2 %>%
  filter(factor == "Positive Urgency")

UPPSP_Exp2_posurgency$resp = as.numeric(as.character(UPPSP_Exp2_posurgency$resp))

# reverse coding positive urgency
UPPSP_Exp2_posurgency = UPPSP_Exp2_posurgency %>%
  mutate(resp_r = 99) %>%
  mutate(resp_r = 5 - resp)

UPPSP_Exp2_posurgency_score = UPPSP_Exp2_posurgency %>%
  group_by(participant) %>%
  summarise(PosUrgency_Score = mean(resp_r))


# negative urgency
UPPSP_Exp2_negurgency = UPPSP_Exp2 %>%
  filter(factor == "Negative Urgency")

UPPSP_Exp2_negurgency$resp = as.numeric(as.character(UPPSP_Exp2_negurgency$resp))

# reverse coding negative urgency
UPPSP_Exp2_negurgency = UPPSP_Exp2_negurgency %>%
  mutate(resp_r = 99) %>%
  mutate(resp_r = 5 - resp)

UPPSP_Exp2_negurgency_score = UPPSP_Exp2_negurgency %>%
  group_by(participant) %>%
  summarise(NegUrgency_Score = mean(resp_r))


# sensation seeking
UPPSP_Exp2_senseek = UPPSP_Exp2 %>%
  filter(factor == "Sensation Seeking")

UPPSP_Exp2_senseek$resp = as.numeric(as.character(UPPSP_Exp2_senseek$resp))

# reverse coding sensation seeking
UPPSP_Exp2_senseek = UPPSP_Exp2_senseek %>%
  mutate(resp_r = 99) %>%
  mutate(resp_r = 5 - resp)

UPPSP_Exp2_senseek_score = UPPSP_Exp2_senseek %>%
  group_by(participant) %>%
  summarise(SenSeeking_Score = mean(resp_r))


# combine all UPPSP factors and prepRT
prepRT2_cor$Perseverance_Score = UPPSP_Exp2_perseverance_score$Perseverance_Score
prepRT2_cor$Premeditation_Score = UPPSP_Exp2_premeditation_score$Premeditation_Score
prepRT2_cor$PosUrgency_Score = UPPSP_Exp2_posurgency_score$PosUrgency_Score
prepRT2_cor$NegUrgency_Score = UPPSP_Exp2_negurgency_score$NegUrgency_Score
prepRT2_cor$SenSeeking_Score = UPPSP_Exp2_senseek_score$SenSeeking_Score


# save as csv
write.csv(prepRT2_cor, 'Exp2_prepRT_UPPSP', row.names = FALSE)
```


```{r Exp 2 TIPI BHI, warning=FALSE, message=FALSE, echo=FALSE}
### TIPI
# check number of participants and number of items across participants
p_TIPI = table(TIPI_Exp2$participant)
#p_TIPI

TIPI_Exp2$resp = as.numeric(as.character(TIPI_Exp2$resp))

# reverse code TIPI question 2
TIPI_Exp2_q1 = TIPI_Exp2 %>%
  filter(qnumber == 1) %>%
  mutate(resp_r = 99) %>%
  mutate(resp_r = resp)

TIPI_Exp2_q2 = TIPI_Exp2 %>%
  filter(qnumber == 2) %>%
  mutate(resp_r = 99) %>%
  mutate(resp_r = 8 - resp)

TIPI_Exp2_new = rbind(TIPI_Exp2_q1, TIPI_Exp2_q2)

# calculate TIPI score (the average of both items)
TIPI_scores = TIPI_Exp2_new %>%
  group_by(participant) %>%
  summarise(TIPI_score = mean(resp_r))

# combine TIPI score and prepRT
prepRT2_cor$TIPI_score = TIPI_scores$TIPI_score


### BHI
p_BHI = table(BHI_Exp2$participant)
#p_BHI

BHI_Exp2$resp = as.numeric(as.character(BHI_Exp2$resp))

# reverse code BHI questions 2 and 4
BHI_Q1 = BHI_Exp2 %>%
  filter(qnumber == 1) %>%
  mutate(resp_r = 99) %>%
  mutate(resp_r = resp)

BHI_Q2 = BHI_Exp2 %>%
  filter(qnumber == 2) %>%
  mutate(resp_r = 99) %>%
  mutate(resp_r = 6 - resp)

BHI_Q3 = BHI_Exp2 %>%
  filter(qnumber == 3) %>%
  mutate(resp_r = 99) %>%
  mutate(resp_r = resp)

BHI_Q4 = BHI_Exp2 %>%
  filter(qnumber == 4) %>%
  mutate(resp_r = 99) %>%
  mutate(resp_r = 6 - resp)

BHI_Exp2_new = rbind(BHI_Q1, BHI_Q2, BHI_Q3, BHI_Q4)

# calculate BHI score (the average of all items)
BHI_scores = BHI_Exp2_new %>%
  group_by(participant) %>%
  summarise(BHI_score = mean(resp_r))

# combine BHI score and prepRT
prepRT2_cor$BHI_score = BHI_scores$BHI_score

# save as csv
write.csv(prepRT2_cor, 'Exp2_prepRT_TIPI_BHI', row.names = FALSE)
```